# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Background color of the statusbar.
# Type: QssColor
c.colors.statusbar.normal.bg = '#2e3440'

# Background color of selected even tabs.
# Type: QtColor
c.colors.tabs.selected.even.bg = '#2e3440'

# Background color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.bg = '#2e3440'

# The height of the completion, in px or as percentage of the window.
# Type: PercOrInt
c.completion.height = '30%'

# Font used in the completion categories.
# Type: Font
c.fonts.completion.category = '12pt Fantasque Sans Mono'

# Font used in the completion widget.
# Type: Font
c.fonts.completion.entry = '12pt Fantasque Sans Mono'

# Default monospace fonts. Whenever "monospace" is used in a font
# setting, it's replaced with the fonts listed here.
# Type: Font
c.fonts.monospace = '"Fantasque Sans Mono", "xos4 Terminus", Terminus, Monospace, "DejaVu Sans Mono", Monaco, "Bitstream Vera Sans Mono", "Andale Mono", "Courier New", Courier, "Liberation Mono", monospace, Fixed, Consolas, Terminal'

# Font used in the statusbar.
# Type: Font
c.fonts.statusbar = '14pt Fantasque Sans Mono'

# Font used in the tab bar.
# Type: QtFont
c.fonts.tabs = '14pt Fantasque Sans Mono'

# The default font size for regular text.
# Type: Int
c.fonts.web.size.default = 16

# Padding for the statusbar.
# Type: Padding
c.statusbar.padding = {'top': 5, 'bottom': 5, 'left': 0, 'right': 0}

# Padding around text for tabs
# Type: Padding
c.tabs.padding = {'top': 5, 'bottom': 5, 'left': 5, 'right': 5}

# Definitions of search engines which can be used via the address bar.
# Maps a searchengine name (such as `DEFAULT`, or `ddg`) to a URL with a
# `{}` placeholder. The placeholder will be replaced by the search term,
# use `{{` and `}}` for literal `{`/`}` signs. The searchengine named
# `DEFAULT` is used when `url.auto_search` is turned on and something
# else than a URL was entered to be opened. Other search engines can be
# used by prepending the search engine name to the search term, e.g.
# `:open google qutebrowser`.
# Type: Dict
c.url.searchengines = {'re': 'https://reddit.com/r/{}',
                       'wi': 'https://en.wikipedia.org/?search={}',
                       'DEFAULT': 'https://duckduckgo.com/?q={}',
                       'yt': 'https://youtube.com/results?search_query={}',
                       'gd': 'https://dict.tu-chemnitz.de/?query={}'}

c.url.start_pages = "https://tbilik.github.io/homepage/index-2.html"
# The default zoom level.
# Type: Perc
c.zoom.default = '110%'
